language: python
python:
- '3.6'
cache:
  pip: true
#env:
#- TEST_SUITE=vale
#- TEST_SUITE=blueberry
#- TEST_SUITE=docs404
 
addons:
  ssh_known_hosts:
  - 73.255.204.36
before_install:
- openssl aes-256-cbc -K $encrypted_07d52615a665_key -iv $encrypted_07d52615a665_iv
  -in scripts/id_rsa.enc -out scripts/.keys/id_rsa -d
- eval "$(ssh-agent -s)"
- cp .scripts/.keys/id_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa

deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master
