language: node_js
node_js:
- "10.0"

#cache:
#  pip: true

dist: trusty
sudo: false

#jobs:
#  include:
#    - stage: "Tests"
#      script: scripts/hello.py
 
addons:
  ssh_known_hosts:
  - 73.255.204.36

before_install:
- openssl aes-256-cbc -K $encrypted_07d52615a665_key -iv $encrypted_07d52615a665_iv
  -in scripts/id_rsa.enc -out scripts/id_rsa -d
- eval "$(ssh-agent -s)"
- cp scripts/id_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
- echo -e "Host 173.255.204.36\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#- sudo apt-get install nodejs
#- npm i -g npm@6
#- npm install --global gatsby-cli

deploy:
- provider: script
  skip_cleanup: true
  local-dir: public
  script: bash scripts/deploy.sh
  on:
    branch: master
